replicas: 1

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    memory: "3Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi

persistence:
  enabled: true

esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    node.name: "elasticsearch-master-0"
    network.host: 0.0.0.0
    discovery.seed_hosts: ["elasticsearch-master-0"]
    cluster.initial_master_nodes: ["elasticsearch-master-0"]
